name: Publish
on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:17-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - run: ./gradlew build publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.NEW_MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.NEW_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEW_MAVEN_PASSWORD }}
          SNAPSHOTS_URL: ${{ secrets.NEW_MAVEN_SNAPSHOT_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.NEW_MAVEN_SNAPSHOT_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.NEW_MAVEN_SNAPSHOT_PASSWORD }}
